export const COPY_USERNAME_TOKEN = "[Username]" as const;

export const copyMatrix = {
  onboarding: {
    signIn: {
      title: "Log in",
      submit: "Log in",
      identifierLabel: "Email or username",
      identifierPlaceholder: "Email or username",
      passwordLabel: "Password",
      forgotPassword: "Forgot password?",
      noAccount: "Don't have an account?",
      createAccount: "Create an account",
      alreadyHaveAccount: "Already have an account?",
      heroLogIn: "Log in",
      forgotUsername: "Forgot username?",
      recoveryEmailLabel: "Email",
      recoveryEmailPlaceholder: "you@example.com",
      recoveryLoginUsernameLabel: "Username",
      recoveryLoginUsernamePlaceholder: "your username",
      recoveryUsernameSubmit: "Send Username",
      recoveryCredentialSubmit: "Send Reset Email",
      recoveryCancel: "Back to log in",
      recoveryUsernameHint:
        "We'll email the username(s) linked to this address. Parents log in with email.",
      recoverySending: "Sending…",
      recoveryUsernameSuccess:
        "If that email is on file, we sent the username there. Check the inbox (and spam).",
      recoveryPasswordHint:
        "Parents and Mavericks: email is enough. If you log in with a username, enter it so we reset that one account.",
      recoveryNeedAccount:
        "Enter the email for that login, or a username that identifies one account.",
      credentialsMismatch:
        "Those details don't match. Check your email or username and password.",
      signInUnavailable: "Could not sign in. Try again shortly.",
      profileOpenFailed: "We could not open your profile. Try again.",
      signingIn: "Signing in…",
    },
    chooseAccount: {
      title: "Who is this account for?",
      learner: "I'm the learner",
      parent: "I'm a parent",
    },
    pendingConsent: {
      heading: "Hang tight. A grown-up needs to approve",
      body: "A parent or guardian has to approve your account before you can keep playing. Your lessons and Points are saved and waiting for you.",
      headingApproved: "You're cleared to play!",
      bodyApproved:
        "Your parent or guardian said yes. Pick up right where you left off.",
      resend: "Resend approval email",
      resending: "Sending…",
      keepPlaying: "Keep playing",
      continue: "Continue in the app",
      logOut: "Back to login",
    },
    approvalSaved: {
      heading: "Approval saved. {username} is active.",
      body: "You can follow their progress in your parent account.",
      logIn: "Log in",
    },
    parentFirstWelcome: {
      heading: "Your parent account is ready",
      intro: "Here is what you can do from here:",
      points: [
        "Follow your child's progress.",
        "Jump into the app yourself if you want.",
        "Build money habits and skills too.",
      ],
      disclaimer:
        "NextGenAchiever$ is an educational tool - not a financial product.",
      cta: "Open Account settings",
    },
  },
  dashboard: {
    greeting: "Hey, [Username]! Let's build wealth.",
    subheading: "Pick your path",
    settings: {
      title: "Settings",
      description:
        "Your account cockpit - manage settings, parent tools, and point conversion.",
      account: {
        passwordReset: "Password Reset",
        passwordResetTitle: "Reset a password",
        passwordResetParentHint:
          "We'll email one reset link for this login.",
        passwordResetChildHint:
          "Learner logins reset through the parent email on file. We'll send a reset link there.",
        passwordResetSubmit: "Send reset email",
        passwordResetSending: "Sending…",
        passwordResetSuccess:
          "If that email is on file, we sent a reset there. Check the inbox (and spam).",
        passwordResetNeedEmail:
          "This profile needs a parent email on file before we can send a reset.",
        passwordResetCancel: "Cancel",
        changeParentPin: "Change Parent PIN",
        accounts: "Accounts",
        subscription: "Subscription",
        logOut: "Log Out",
        birthYearTrack: "Birth Year / Age Track",
      },
      accountSubscription: {
        title: "Family accounts",
        description: "Manage your master account and linked learners.",
        backLabel: "Back to Settings",
        accountsHeading: "Accounts",
        masterBadge: "Master account",
        childBadge: "Learner account",
        emptyChildren: "No linked learner accounts yet.",
        addLinkedProfile: "Add profile",
        addProfile: "Add a child",
        linkProfile: "Approve profile",
        addLinkedTitle: "Add profile",
        addLinkedTrackHeading: "Pick their learning track",
        addLinkedTrackHint:
          "Choose the age range that matches this learner. That sets their tools and content.",
        addLinkedContinue: "Continue",
        addLinkedDetailsHeading: "Set their login",
        addLinkedDetailsHint:
          "They join your household as approved. Username and password recovery uses your email.",
        addLinkedUsernameLabel: "Username",
        addLinkedPasswordLabel: "Password",
        addLinkedConfirmPasswordLabel: "Confirm password",
        addLinkedParentEmailLabel: "Parent email",
        addLinkedParentEmailHint:
          "This is your signed-in email. Recovery for you and this learner uses this address.",
        addLinkedSubmit: "Add profile",
        addLinkedSubmitting: "Adding…",
        addLinkedBackTrack: "Back to track",
        addLinkedBackAccounts: "Back to Accounts",
        addLinkedNeedParent: "Create your parent profile first before you can add a child.",
        addLinkedNeedEmail:
          "Your parent account needs an email before you can add a profile.",
        needParentPrompt:
          "Create your parent profile first. Then you can add or link a learner.",
        createParentTitle: "Create your parent profile",
        createParentHint:
          "This is your master login. After this, you can add a child or link a pending request.",
        createParentEmailLabel: "Your email",
        createParentEmailHint:
          "This email is your parent login, and recovery for you and linked learners uses this address.",
        createParentUsernameLabel: "Your username",
        createParentPasswordLabel: "Password",
        createParentConfirmPasswordLabel: "Confirm password",
        createParentSubmit: "Create parent profile",
        createParentSubmitting: "Creating…",
        noAccountsYet: "No registered accounts found for this session.",
        guestEmptyHint:
          "You're in a temporary session. Create an account to keep this progress.",
        guestCreateParent: "Create parent account",
        guestSaveLearner: "Save learner progress",
        pendingHeading: "Waiting to link",
        pendingHint:
          "These learners asked for approval with your email. Link them here, or use the email approval link.",
        linkingProfile: "Approving…",
        deleteChild: "Delete account",
        deleteChildNamed: "Delete {username} account",
        deleteSectionHeading: "Remove accounts",
        approveChild: "Approve profile",
        approveChildError:
          "We could not approve this learner. Try again or use the approval email link.",
        pendingApprovalBadge: "Pending approval",
        deleteMaster: "Delete master account",
        deleteMasterHint:
          "This deletes your account and all associated child accounts.",
        childRowManage: "Manage",
        deleteChildTitle: "Delete learner account?",
        deleteChildConfirm:
          "Delete this learner account? This will permanently remove all data associated with the account - including progress, achievements, and activity - and cannot be undone.",
        deleteMasterTitle: "Delete master account?",
        deleteMasterConfirm:
          "This cannot be undone. Deleting your master account will permanently remove:",
        deleteMasterConfirmParent: "your parent / master account",
        deleteMasterConfirmChildren: "ALL linked child / learner accounts",
        deleteMasterConfirmData: "associated progress and account data",
        deleteMasterAcknowledge:
          "I understand this permanently deletes my household.",
        deleteMasterDeleting: "Deleting…",
        deleteMasterError:
          "We could not delete this household. Your parent login is still active. Try again.",
        deleteConfirmAction: "Delete permanently",
        deleteCancelAction: "Cancel",
        learningPathLabel: "Learning path",
        changeTrack: "Change path",
        changeTrackClose: "Close",
        changeTrackError: "We could not update this learning track. Try again.",
        changeTrackConfirmTitle: "Change learning track?",
        changeTrackConfirmSwitch:
          "Switch {username} to {track}?",
        changeTrackConfirmReset:
          "Changing track resets this learner's Academy progress and skill trophies.",
        changeTrackConfirmAge:
          "Each track is age-specific. Lessons, scenarios, and skills match that age band - for example, a 10-year-old should not be on Maverick.",
        changeTrackConfirmAction: "Change track",
        changeTrackCancelAction: "Cancel",
      },
      subscription: {
        title: "Subscription",
        description: "Manage your NextGenAchievers plan.",
        backLabel: "Back to Settings",
        placeholder: "Subscription management coming soon.",
      },
      profile: {
        joinDateLabel: "Joined",
      },
      parentMode: {
        label: "Parent Mode",
        shortLabel: "Parent",
        enabledHint: "Preferences unlocked - you can adjust these settings.",
        pinTitle: "Parent PIN Required",
        pinBody:
          "Enter the parent PIN to open Preferences. Conversion rate and learning track stay under master control.",
        setupTitle: "Set Parent PIN",
        setupBody:
          "No parent PIN yet. Choose a 4-digit code to secure Preferences.",
        setupNewLabel: "New PIN",
        pinPlaceholder: "4-digit PIN",
        setupConfirmLabel: "Confirm new PIN",
        pinError: "Wrong PIN - nice try.",
        setupMismatch: "PINs don't match - try again.",
        pinConfirm: "Unlock Preferences",
        setupSave: "Save & Unlock Preferences",
        pinCancel: "Cancel",
      },
      parentHub: {
        title: "Preferences",
        lockedSubtext: "PIN required for master controls",
        unlockedSubtext: "Tap a feature to expand and manage it",
        lockedBadge: "Locked",
        unlockedBadge: "Open",
        unlockButton: "Enter Parent PIN",
        lockHub: "Lock Preferences",
      },
      parentHubFeatures: {
        pointsConversion: "Coins exchange rate",
        pointsConversionSummaryLocked: "Set how coins convert to in-app money",
        pointsConversionNotSet: "Not set yet",
        learningTrack: "Change learning track",
        learningTrackSummaryLocked: "View and update the learner age track",
        currency: "Display currency",
        currencySummaryLocked: "Choose currency shown in Vault",
      },
      learningTrack: {
        intro:
          "Each learning track is built for a specific age band — lessons, scenarios, and skills match how learners that age think and operate.",
        tierUpdateNote:
          "Changing the learner tier updates Academy content to age-relevant scenarios and skills.",
        progressResetWarningTitle: "Progress reset",
        progressResetWarning:
          "Switching tracks resets Academy lesson progress and skill trophies. Vault balances and coins stay put.",
        progressResetConfirmed:
          "Academy progress and skill trophies were reset for the new track.",
        currentBadge: "Current",
        agesTemplate: "Ages {range}",
        skillsTemplate: "{count} skills",
        birthYearLabel: "Birth year",
        save: "Save Track",
        savedTitle: "Track Updated",
        savedBodyTemplate:
          "Birth year saved. You are now on the {track} track (ages {range}).",
        savedAcknowledge: "Got it",
        invalidYear: "Pick a valid birth year.",
        unchanged: "That birth year is already saved.",
        lockedHint: "Unlock Preferences to change the learning track.",
      },
      currency: {
        heading: "Display currency",
        summary:
          "Shown in Vault and coins cash-in. Amounts stay the same, only the symbol changes.",
        lockedHint: "Currency can be changed anytime in Settings.",
        savedNote: "Currency updated across Vault.",
      },
      birthYear: {
        pinBody:
          "Enter the parent PIN to update birth year and learning track.",
        modalTitle: "Update Birth Year",
        modalBody:
          "Pick the correct birth year. Academy modules, skills, and lessons will match the new age track.",
        currentTrackLabel: "Current track",
        newTrackLabel: "New track",
        birthYearLabel: "Birth year",
        save: "Save Birth Year",
        cancel: "Cancel",
        savedTitle: "Track Updated",
        savedBodyTemplate:
          "Birth year saved. You are now on the {track} track (ages {range}).",
        savedAcknowledge: "Got it",
        invalidYear: "Pick a valid birth year.",
        unchanged: "That birth year is already saved.",
      },
      changePin: {
        title: "Change Parent PIN",
        body: "Verify your current PIN, then set a new 4-digit parent code.",
        currentLabel: "Current PIN",
        newLabel: "New PIN",
        confirmLabel: "Confirm new PIN",
        currentError: "Current PIN doesn't match.",
        newInvalid: "New PIN must be exactly 4 digits.",
        mismatch: "New PINs don't match - try again.",
        sameAsOld: "Pick a different PIN than your current one.",
        forgotPin: "Forgot PIN?",
        forgotPinSending: "Sending recovery code…",
        forgotPinSuccess:
          "Recovery code {code} sent to {email}. Use it as your current PIN, then set a new one.",
        save: "Save New PIN",
        cancel: "Cancel",
      },
      conversion: {
        heading: "Coins exchange rate",
        rateTemplate: " coins = $1.00 AUD",
        summary:
          "When your child cashes in coins, converted cash goes into their Save Jar at this rate.",
        vaultCashInHint:
          "Open parent Settings to set the coins exchange rate. Kids cash in from the coins icon.",
        unsetHint:
          "Save a rate so your child can exchange coins for in-app money.",
        saveRate: "Save rate",
        convertNowHeading: "Convert Now",
        convertFullBalance: "Use all coins",
        customAmountLabel: "Coins to exchange",
        customAmountPlaceholder: "Enter coins amount",
        invalidAmountError: "Enter how many coins you want to exchange.",
        overBalanceError: "That's more coins than you have right now.",
        payoutReadoutTemplate:
          "This will send {amount} to the child's unallocated income pool",
        sendToVault: "Send to Vault",
        disclaimer:
          "Disclaimer: NextGenAchievers is a financial literacy utility. This platform does not process real-world monetary transactions, bank transfers, or legal cash deposits. All balances represent virtual learning values.",
        confirmTitle: "Virtual Transfer Reminder",
        confirmBody:
          "This action does not move real money. The cash amount displayed is a virtual representation for your child's ledger. You will need to fulfill this payout independently via cash, allowance pocket money, or your preferred banking app.",
        confirmAcknowledge: "Got it",
        cashInHeading: "Exchange coins",
        cashInRateHint: "Rate: {rate}",
        rateNotSetHint: "Rate: not set yet",
        xpAvailableTemplate: "{points} coins available",
        noPointsError: "No coins to cash in yet. Keep learning!",
        claimingLabel: "Exchanging…",
        childPayoutReadoutTemplate: "You'll get {amount} in your Save Jar",
        claimCashReward: "Confirm",
        successTitle: "Points Converted!",
        successBodyTemplate:
          "Points Converted! {amount} has been safely deposited straight into my Save Jar. Head over to the Vault to check my growth, or shift my funds to another jar if I have a different plan!",
        successAcknowledge: "Let's Go!",
        askParentTitle: "Your coins",
        askParentWhat:
          "Coins are what you earn by finishing Academy lessons and activities.",
        askParentExchange:
          "Once a parent sets an exchange rate, you can turn coins into in-app money for your Save Jar.",
        askParentBody:
          "Ask your parent to set that rate in Settings. Then you can cash in right here.",
        askParentIfParentBody:
          "Set the coins exchange rate in Settings. Then coins can be cashed in here.",
        parentEmail: {
          draftLabel: "Parent notification",
          title: "Email sent to guardian",
          body: "We sent a heads-up about this coins cash-in. Draft preview below.",
          toLabel: "To:",
          subjectLabel: "Subject:",
          acknowledge: "Got it",
        },
      },
    },
    academy: {
      title: "Academy",
      description:
        "Bite-sized learning missions. Master the 24 core financial skills through interactive games.",
      journey: {
        heading: "Your Mission Map",
        xpLabel: "coins",
        lockedLabel: "Locked",
        skillsCupLabel: "Skills",
        skillsCupTip: "Your medals live in the cup. Tap it anytime.",
        nodes: [
          {
            id: "cash-stash",
            number: 1,
            subtitle: "How the Money Game Works",
            focusAreas: "Money is a tool to buy freedom and choices",
            iconPath: "/dashboard/money-bag.svg",
          },
          {
            id: "leveling-up-loot",
            number: 2,
            subtitle: "Protecting Your Money",
            focusAreas: "Money is lost when you can't see what's happening",
            iconPath: "/dashboard/trend-up.svg",
          },
          {
            id: "interest-multiplier",
            number: 3,
            subtitle: "Taking Control of Your Money",
            focusAreas: "If you don't control money, it controls you",
            iconPath: "/dashboard/bank-building.svg",
          },
          {
            id: "goal-crusher",
            number: 4,
            subtitle: "Generating Your Own Income",
            focusAreas: "Money comes from creating value for others",
            iconPath: "/dashboard/goal-target.svg",
          },
          {
            id: "scammer-defense",
            number: 5,
            subtitle: "Growing Your Money",
            focusAreas: "Money grows when it is put to work",
            iconPath: "/dashboard/shield-check.svg",
          },
          {
            id: "savings-streak",
            number: 6,
            subtitle: "Structuring & Optimising Your Money",
            focusAreas:
              "How you structure money determines how much you keep and grow",
            iconPath: "/dashboard/piggy-bank.svg",
          },
        ],
      },
    },
    launchpad: {
      title: "Business Launchpad",
      description:
        "Launch your business. Two starter ventures are free — unlock the rest with Premium.",
    },
    community: {
      title: "Community",
      description:
        "Monthly challenges and the friends leaderboard — see how you stack up.",
    },
    vault: {
      title: "Vault",
      description:
        "My wealth cockpit. Track my assets, revenue, and watch my net worth climb.",
      cashInTileLabel: "Cash In My Points",
      cashInTileSubtext: "{points} coins ready to convert",
      budget: {
        sectionTitle: "Budget Allocation",
        depositHeading: "Got some money? Add it here!",
        depositSectionDisclaimerLead:
          "Enter real-world cash from allowance, jobs, or gifts to practice budgeting in ",
        depositSectionDisclaimerEmphasis: "this virtual learning simulator",
        depositSectionDisclaimerRest:
          ". Nothing here connects to real bank accounts, payments, or financial institutions.",
        depositButton: "Deposit Income",
        poolLabel: "Money to Allocate",
        currencySettingsNote:
          "Currency can be changed in Settings → Preferences.",
        remainingLabel: "Money to allocate",
        toAllocateAmountTemplate: "+{amount}",
        toAllocateActionLabel: "to allocate",
        toAllocateAriaLabel: "Go to allocation: {amount} to allocate",
        fullyAllocatedLabel: "Fully Allocated!",
        lockItIn: "Allocate Now",
        move: "Move",
        spendAction: "Spend",
        moveAction: "Move",
        deleteBucket: "Delete bucket",
        deleteBucketDisabledHint: "Empty this bucket before deleting it.",
        spendCategoryLabel: "Category",
        spendAmountLabel: "Amount",
        spendConfirm: "Spend",
        actionCancel: "Cancel",
        bucketEmptyHint: "Nothing in this bucket yet.",
        manageSpendingCategories: "Manage Spending Categories",
        manageCategoriesHeading: "My spending categories",
        customCategoryPlaceholder: "New category name",
        addCategory: "Add Category",
        premiumCategoriesTitle: "Custom Spending Categories",
        premiumCategoriesBody:
          "Premium lets me rename the built-in categories and add my own. Perfect when my spending style is more than snacks and fun.",
        defaultCategories: {
          foodSnacks: "Food & Snacks",
          funEntertainment: "Fun & Entertainment",
          personalItems: "Personal Items",
          gifts: "Gifts",
          other: "Other",
        },
        markAsSpent: "Mark as Spent",
        inJarTemplate: "{amount}",
        fromPoolLabel: "From this deposit",
        addCustomBucket: "Add Budget Jars",
        renameBucket: "Rename",
        bucketLimitTemplate: "{count} / {max} buckets",
        premiumRenameTitle: "Level Up My Vault",
        premiumRenameBody:
          "Renaming Save, Spend, and Give is a Premium perk. Freemium keeps the classic trio - upgrade to name them my way.",
        premiumUnlock: "Unlock Premium Tier",
        premiumLater: "Maybe later",
        moveTitle: "Move Money",
        markSpentTitle: "Mark as Spent",
        moveAmountLabel: "Amount to move",
        markSpentAmountLabel: "Amount spent",
        moveDestinationLabel: "Move to",
        moveConfirm: "Move It",
        markSpentConfirm: "Log It",
        moveCancel: "Cancel",
        movePoolOption: "Money to Allocate",
        spentLogTemplate: "Spent {amount} on {category} from {bucket}",
        lockedInTemplate: "Locked {amount} into my jars",
        depositLogTemplate: "Deposited {amount} from {source} to allocate",
        bucketsOverviewTitle: "My Budget Items",
        allocateHeading: "Split It Up",
        totalBalanceLabel: "My Money",
        virtualMoneyDisclaimer:
          "This is a virtual learning simulator for practicing real-world financial management. Nothing here connects to real bank accounts, payments, or financial institutions.",
        futurePotentialLabel: "Future Potential",
        currentSavingsLabel: "Current Savings",
        changeLimitsLink: "Change limits",
        premiumCompoundingTitle: "Custom Calculator Limits",
        premiumCompoundingBody:
          "Premium unlocks longer timelines (up to 30 years) and bigger weekly top-ups (up to $100). Tune the compound calculator to match my real savings plan.",
        weeklyTopUpLabel: "Weekly Top-Up",
      },
      savings: {
        sectionTitle: "Savings Goals",
        totalSavingsLabel: "Total Savings",
        savingsToAllocateLabel: "Savings to Allocate",
        clickToAllocateHint: "click to allocate",
        setOrChangeSavingsTarget: "Set or Change Savings Target",
        currentProgressHeading: "Current progress",
        setGoalConfirm: "Set",
        spendMoney: "Spend money",
        moveMoney: "Move money",
        moveSourceLabel: "Move from",
        unallocatedSourceLabel: "Unallocated",
        moveConfirm: "Move",
        vaultTransferLogTemplate: "Moved {amount} from {from} to {to}",
        percentToTargetTemplate: "{percent}% to target",
        changeGoalTargetHint: "Set a target amount for this goal (optional). You can do this anytime.",
        goalTargetUnset: "Not set",
        goalTargetUpdatedTemplate: "Updated {goal} target to {amount}",
        manageSavingsGoals: "Manage Savings Goals",
        firstGoalsCallout: "Set your first savings goals now!",
        noGoalsYet: "No savings goals yet.",
        goalHitTargetLogTemplate: "{goal} hit its savings target. Nice work!",
        goalAchievedCallout: "Savings goal achieved!",
        goalAchievedCalloutKicker: "Nice work!",
        goalEmptyHint: "Nothing saved in this goal yet.",
        addGoal: "Add Savings Goal",
        premiumGoalsTitle: "Multiple Savings Goals",
        premiumGoalsBody:
          "Premium lets me set named targets, track progress bars, and allocate straight from my Save Jar. One goal is great - several is founder mode.",
        goalNameLabel: "Goal name",
        goalTargetLabel: "Target amount",
        createGoal: "Create Goal",
        assignToGoals: "Allocate Now",
        goalAllocationHeading: "Allocate to Goals",
        goalRemainingLabel: "Left to assign",
        fullyAllocatedLabel: "Fully Allocated!",
        allocatedToGoalTemplate: "Moved {amount} to {goal}",
        spentFromGoalTemplate: "Spent {amount} from {goal}",
        spentFromGoalWithNoteTemplate: "Spent {amount} from {goal} on {note}",
        spendOnLabel: "What for? (optional)",
        spendAmountLabel: "Amount",
        spendGoalConfirm: "Spend",
        spendConfirm: "Log It",
        spendCancel: "Cancel",
      },
      ledger: {
        titleTemplate: "{name}'s Ledger",
        subtitle: "Money in and out",
        periodWeek: "Week",
        periodMonth: "Month",
        periodYear: "Year",
        periodAll: "All-Time",
        moneyInLabel: "Money In",
        moneyOutLabel: "Money Out",
        inflowsHeading: "Inflows",
        outflowsHeading: "Outflows",
        activityHeading: "Activity",
        emptyPeriod: "Nothing logged for this period yet.",
        welcomeMessage: "Vault online! Deposit income, funnel it into jars, and stack wins.",
        categories: {
          deposit: "Deposit",
          cash_in: "Coins Cash-In",
          allocation: "Jar Allocation",
          spend: "Spending",
          transfer: "Transfer",
          savings_goal: "Savings Goal",
          goal_spend: "Goal Spend",
          milestone: "Milestone",
          setup: "Setup",
          info: "Update",
        },
      },
    },
    achievements: {
      title: "Achievements",
      description:
        "Your skill cabinet - track Locked, Unlocked, Bronze, Silver, and Gold across your learning track.",
    },
  },
  home: {
    streak: {
      label: "Day Streak",
      unit: "days",
    },
    shield: {
      label: "Banked Streak Freezes",
      activeLabel: "Freezes Active",
    },
    skillTrack: {
      heading: "Skills Unlocked",
      progressLabel: "Progress",
      lockedLabel: "Locked",
    },
    skillNodes: [
      {
        id: "level-1",
        title: "How the Money Game Works",
        subtext: "Money is a tool to buy freedom and choices",
      },
      {
        id: "level-2",
        title: "Protecting Your Money",
        subtext: "Money is lost when you can't see what's happening",
      },
      {
        id: "level-3",
        title: "Taking Control of Your Money",
        subtext: "If you don't control money, it controls you",
      },
      {
        id: "level-4",
        title: "Generating Your Own Income",
        subtext: "Money comes from creating value for others",
      },
      {
        id: "level-5",
        title: "Growing Your Money",
        subtext: "Money grows when it is put to work",
      },
      {
        id: "level-6",
        title: "Structuring & Optimising Your Money",
        subtext:
          "How you structure money determines how much you keep and grow",
      },
    ],
  },
} as const;

export type DashboardCopyPillar = keyof Pick<
  typeof copyMatrix.dashboard,
  "settings" | "academy" | "launchpad" | "community" | "vault" | "achievements"
>;
