/** Vault dashboard copy. */
export const vaultCopy = {
  title: "Vault",
  description: "Manage your money, jars, and deposits.",
  allocationSectionTitle: "Allocate Money",
  closeModalLabel: "Close",
  backToOverview: "Back to overview",
  budgetJarsSectionLabel: "Budget Jars",
  manageBudgetJarsLabel: "Manage Budget Jars",
  manageBudgetJarsTitle: "Manage Budget Jars",
  manageBudgetJarsBody:
    "Rename jars, pick icons, add custom buckets, or remove ones you no longer need.",
  addBudgetJar: "Add Budget Jar",
  jarNameLabel: "Jar name",
  jarNamePlaceholder: "My jar",
  jarIconLabel: "Icon",
  deleteJarConfirmTitle: "Delete this jar?",
  deleteJarConfirmBody: "This cannot be undone. The jar will be removed from your vault.",
  deleteJarWithBalanceBody:
    "This jar still has money in it. Pick another jar to receive the balance before deleting.",
  deleteJarFallbackLabel: "Move balance to",
  deleteJarConfirm: "Delete jar",
  bucketLimitTemplate: "{count} / {max} jars",
  saveChanges: "Save Changes",
  cancelChanges: "Cancel",
  editJar: "Edit jar",
  deleteJar: "Delete jar",
  addJarToList: "Add to list",
  doneEditing: "Done",
  manageSavingsGoalsLabel: "Manage Goals",
  manageSavingsGoalsTitle: "Manage Savings Goals",
  manageSavingsGoalsBody:
    "Set targets, rename goals, add custom savings goals, or reset a goal balance. Clearing a target never wipes saved progress.",
  goalSettingsLabel: "Goal Settings",
  addSavingsGoal: "+ Add Goal",
  goalNameLabel: "Goal name",
  goalTargetLabel: "Target amount",
  goalIconLabel: "Icon",
  saveGoalChanges: "Save Changes",
  resetGoalBalance: "Reset Balance",
  resetGoalBalanceConfirmTitle: "Reset this goal balance?",
  resetGoalBalanceConfirmBody:
    "Are you sure you want to reset this item to $0? Saved progress in this goal will be cleared.",
  resetBucketBalance: "Reset Balance",
  resetBalanceToZero: "Reset balance to zero",
  setAllBalancesToZero: "Set all balances to zero",
  resetBucketBalanceConfirmTitle: "Reset this jar balance?",
  resetBucketBalanceConfirmBody:
    "Are you sure you want to reset this item to $0? Money in this jar will be cleared.",
  resetAllGoalBalancesConfirmTitle: "Set all goal balances to $0?",
  resetAllGoalBalancesConfirmBody:
    "Are you sure you want to reset every savings goal balance to $0? Saved progress in these goals will be cleared.",
  resetAllBalances: "Reset All Balances",
  resetAllBalancesConfirmTitle: "Reset everything to $0?",
  resetAllBalancesConfirmBody:
    "Are you sure you want to reset ALL jars, goals, and income balances to $0? This cannot be undone.",
  resetConfirm: "Yes, reset",
  resetCancel: "Cancel",
  maxAmountReachedNotice: "Maximum amount reached",
  premiumGoalsLockedTitle: "Premium Savings Goals",
  premiumGoalsLockedBody:
    "Premium unlocks custom savings goals beyond your two starter targets.",
  deleteGoal: "Delete goal",
  deleteGoalConfirmTitle: "Delete this goal?",
  deleteGoalConfirmBody: "This custom goal will be removed from your vault.",
} as const;
